### ISSUE TITLE
Change close X Icon to a svg file

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#18]
Instead of using the letter X, use a **SVG** of an X.

maybe this one: https://fontawesome.com/icons/x?s=solid&f=classic

feel free to use good looking other

![grafik](https://user-images.githubusercontent.com/6397577/193425091-db98f239-0029-4285-ab78-a84943a96a30.png)

**Comment by eemike07** [comment]
Hello, can you assign this one to me?

Thank you :)

**Comment by alkhimch** [comment]
@eemike07 can you still handle this task ?

**Comment by eemike07** [comment]
Yes, I'm about to push this.  I've added FontAwesome library and replaced the X btn.  Also added a cookie svg :)

**Comment by Gismo1337** [comment]
I did my review. please use SVG as described and don't add fontawesome or something like this. Only SVG. Loading font awesome dependecy is to complex for this small package.

**Comment by eemike07** [comment]
Pushed up changes.  Sorry about that.
