### ISSUE TITLE
Write Checkbox Subtext to explain cookie

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#2]
![grafik](https://user-images.githubusercontent.com/6397577/193404312-86700ede-dd72-424b-b2cb-779e958bdd7c.png)
Code a subtext for each checkbox to describe the individual cookie in detail.

**Comment by superiorsd10** [comment]
@Gismo1337 I would like to work on this. Can you please assign it to me?

**Comment by Gismo1337** [comment]
> @Gismo1337 I would like to work on this. Can you please assign it to me?

done. have fun!

**Comment by Gismo1337** [comment]
@superiorsd10 do you working on this?

**Comment by superiorsd10** [comment]
@Gismo1337 Yes, I'll make a PR soon.
