### ISSUE TITLE
Create a SFC for the Buttons

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#28]
## **Is your feature request related to a problem? Please describe.**

* Request

---

## **Describe the solution you'd like**

* Write a Button Single File Component to upgrade the readability

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by MoskalykA** [comment]
Can you assign me to this please

**Comment by Gismo1337** [comment]
done @MoskalykA

**Comment by Gismo1337** [comment]
@MoskalykA  do you working on this?

**Comment by MoskalykA** [comment]
> @MoskalykA do you working on this?

I wanted to get back to Vue with this issue but I can't, I prefer to leave it to another person

**Comment by Gismo1337** [comment]
assigned @probablyArth

**Comment by probablyArth** [comment]
yess
