### ISSUE TITLE
[Bug] VUE Warn

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#29]
### **Describe the bug**

* Check the vue warning in console and fix them

---

### **Is this a regression?**

---

### **To Reproduce**

1. Open Console
2. Click Accept
3. Check console

---

### **Expected behaviour**

* No warnings

---

### **Media prove**

![grafik](https://user-images.githubusercontent.com/6397577/193445835-0ff4afdf-5ec4-4009-ba3c-b6bc415899b2.png)

---

### **Your environment**

* OS: 
* Node version:
* Npm version:
* Browser name and version:

---

### **Additional context**

*

**Comment by Adnan-Sait** [comment]
I would love to work on this issue.
Could you assign it to me?

**Comment by Gismo1337** [comment]
> I would love to work on this issue.
> Could you assign it to me?

you can start @Adnan-Sait

I assign you
