### ISSUE TITLE
Page has a vertical scroll

### ISSUE THREAD

**Issue by Adnan-Sait** [Gismo1337/vue-cookie-consent-banner#38]
### **Describe the bug**
The page is having a scroll bar with its minimum height set.
This is due to the margin-top set on the main element.

---

### **Is this a regression?**

---

### **To Reproduce**

1. Open the main page
2. Accept / Decline the cookies
3. You will see the vertical scroll on the page

### **Expected behaviour**

The page should not have a vertical scroll unless the content overflows the window height.

---

### **Media prove**
![Screenshot (31)](https://user-images.githubusercontent.com/59290226/193466522-b68f5bd2-faa2-4e10-a6ee-c8c1de2a4e5b.png)

---

### **Your environment**

* OS: Windows 11
* Browser name and version: Chrome - 106.0.5249.62

---

**Comment by Gismo1337** [comment]
❤️

**Comment by thisiskaransgit** [comment]
Hey @Gismo1337, I have fixed the issue,  kindly review the PR!
