### ISSUE TITLE
Please increase the font size of the title

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#43]
## **Is your feature request related to a problem? Please describe.**

* Request

---

## **Describe the solution you'd like**

* Please increaste the font size of the title to the same size of the X to close the modal. You can try to add more size than the X, if its looks good.

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

* 
![grafik](https://user-images.githubusercontent.com/6397577/193866126-5b6410b7-b112-4607-8ad5-d242a782b94b.png)

**Comment by aswinikalyan30** [comment]
Hey, can i take this up?

**Comment by HridoyHazard** [comment]
can i take it plz

**Comment by Gismo1337** [comment]
first in, first out. assigned @aswinikalyan30
