### ISSUE TITLE
Create a Section SFC

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#46]
## **Is your feature request related to a problem? Please describe.**

* Enhancement

---

## **Describe the solution you'd like**

* Outsource the <section id="options"> into a single file component. Filename: OptionSection.vue

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by taramatt93** [comment]
I can take this one!

**Comment by Gismo1337** [comment]
assigned @taramatt93
