### ISSUE TITLE
Create a Footer SFC

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#47]
## **Is your feature request related to a problem? Please describe.**

* Enhancement

---

## **Describe the solution you'd like**

* Outsoruce the footer into a Singel File Component. Watchout! Slot couldt be passed sometimes and the Button Functions are needed.  Filename: FooterSection.vue 

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by taramatt93** [comment]
I can take this issue!

**Comment by Gismo1337** [comment]
@taramatt93 Assigned you! Have a good time solving this 💯

**Comment by taramatt93** [comment]
I'm looking forward to it! Could I ask what you want me to do with the slot, as you've said 'Slot could be passed sometimes'?

**Comment by Gismo1337** [comment]
there are slots reserved to pass individual title and body text in the cookiemodal.
