### ISSUE TITLE
Add Screen reader ability

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#48]
## **Is your feature request related to a problem? Please describe.**

* Enhancement

---

## **Describe the solution you'd like**

* Add needed HTML Code to be Screen Reader ready.

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

**Comment by taramatt93** [comment]
I can have a go at this - haven’t done much with screen readers before, but would love to see how it goes!

**Comment by Gismo1337** [comment]
go for it @taramatt93 . its really simple. you shouldt google: `aria-label and class="sr-only"`
