### ISSUE TITLE
[Bug] Cookie name and subtext are not clickable

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#51]
### **Describe the bug**

* When you hover the text after the chackbox, the mouse switch to pointer, but there is nothing clickable.

---

### **Is this a regression?**

---

### **To Reproduce**

1. open options
2. mouseover text
3. the mousecursor change to pointer
4.

---

### **Expected behaviour**

* Make the text clickable to check the box false and true OR disable the mouseover

---

### **Media prove**

---

### **Your environment**

* OS: 
* Node version:
* Npm version:
* Browser name and version:

---

### **Additional context**

*

**Comment by Aspireve** [comment]
Hey @Gismo1337 !!
Could I work on this?

**Comment by Gismo1337** [comment]
assigned @Aspireve

**Comment by mahamat-abdelkerim-abakar** [comment]
could i work on this?

**Comment by Gismo1337** [comment]
If Aspireve surrender =) I ping you here @mahamat-abdelkerim-abakar

**Comment by Aspireve** [comment]
Hi @Gismo1337 , So I have to remove the mouse pointer right?

**Comment by Gismo1337** [comment]
please read the ticket :-)

**Comment by Gismo1337** [comment]
looks good for me @Aspireve

**Comment by Aspireve** [comment]
Yoo Thanks!! I'll make my PR then (my first one for the HacktoberFest 🥳🥳!!)
