### ISSUE TITLE
[Bug] Center X Icon and Title Text

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#54]
### **Describe the bug**

* The Title "Cookie Consent" is not on the same level with the closing X.

---

### **Is this a regression?**

---

### **To Reproduce**

1.
2.
3.
4.

---

### **Expected behaviour**

* Center them horizontal

---

### **Media prove**

![grafik](https://user-images.githubusercontent.com/6397577/194091054-17ed3850-016e-452e-bc81-c89c55ea2496.png)
---

### **Your environment**

* OS: 
* Node version:
* Npm version:
* Browser name and version:

---

### **Additional context**

*

**Comment by taramatt93** [comment]
I can take this if you're happy for me to!

**Comment by tech0x10** [comment]
hey if i have a quick solution for this one, let me give a chance

**Comment by taramatt93** [comment]
I’m afraid I’ve got it ready for PR now, will be submitting within the next hour so I’m holding on to it
