### ISSUE TITLE
Write a issue template

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#6]
In order for beginners in the field of OpenSource to enjoy working together, we need a Issue template.

Please look at some good examples on the internet and provide something appropriate.

Thanks a lot

**Comment by VividhPandey003** [comment]
Hey @Gismo1337 👋. I am a beginner to Open Source and really looking forward to contribute. Could you please assign this issue to me under Hacktoberfest

**Comment by Gismo1337** [comment]
> Hey @Gismo1337 👋. I am a beginner to Open Source and really looking forward to contribute. Could you please assign this issue to me under Hacktoberfest

did it.
have fun!

**Comment by rising-star2712** [comment]
hi , @Gismo1337 , could I work on this issue , I am beginner to open source , and willing to contribute in this issue for Hacktober fest

**Comment by Gismo1337** [comment]
@rising-star2712 please get in touch with @VividhPandey003 . I already assign her/him

**Comment by VividhPandey003** [comment]
Hey👋, @rising-star2712; Actually I am currently working on this issue.😅

**Comment by rising-star2712** [comment]
ok @VividhPandey003

**Comment by VividhPandey003** [comment]
@Gismo1337 Should I create a general template or I was thinking to divide it into different readmes' like bug report, feature request. Can you please guide me regarding this

**Comment by Gismo1337** [comment]
@VividhPandey003 i think one general would be enough for this little project. but i wont restrict this. if you think its a good idea, feel free

**Comment by VividhPandey003** [comment]
Okay, Thank You. @Gismo1337

**Comment by VividhPandey003** [comment]
Thank You @Gismo1337
