### ISSUE TITLE
Write a PR template

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/vue-cookie-consent-banner#7]
In order for beginners in the field of OpenSource to enjoy working together, we need a Pull Request template.

Please look at some good examples on the internet and provide something appropriate.

Thanks a lot

**Comment by nabeel001** [comment]
Hi @Gismo1337 , I would like to work on this issue, Can you please assign this to me

**Comment by Gismo1337** [comment]
> Hi @Gismo1337 , I would like to work on this issue, Can you please assign this to me
> 

done. have fun

**Comment by nabeel001** [comment]
Ok Thank You
